<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('home_settings', function (Blueprint $table) {
            $table->id();
            $table->string('title_one')->nullable();
            $table->string('title_one_ar')->nullable();
            $table->string('title_two')->nullable();
            $table->string('title_two_ar')->nullable();
            $table->string('paragraph_one')->nullable();
            $table->string('paragraph_one_ar')->nullable();
            $table->string('btn_one_txt')->nullable();
            $table->string('btn_one_txt_ar')->nullable();
            $table->string('title_three')->nullable();
            $table->string('title_three_ar')->nullable();
            $table->string('sub_title_no_one')->nullable();
            $table->string('sub_title_no_one_ar')->nullable();
            $table->string('title_four')->nullable();
            $table->string('title_four_ar')->nullable();
            $table->string('sub_title_one')->nullable();
            $table->string('sub_title_one_ar')->nullable();
            $table->string('sub_title_two')->nullable();
            $table->string('sub_title_two_ar')->nullable();
            $table->string('sub_title_three')->nullable();
            $table->string('sub_title_three_ar')->nullable();
            $table->string('sub_title_four')->nullable();
            $table->string('sub_title_four_ar')->nullable();
            $table->string('sub_title_five')->nullable();
            $table->string('sub_title_five_ar')->nullable();
            $table->string('sub_title_six')->nullable();
            $table->string('sub_title_six_ar')->nullable();
            $table->string('paragraph_two')->nullable();
            $table->string('paragraph_two_ar')->nullable();
            $table->string('sub_title_no_two')->nullable();
            $table->string('sub_title_no_two_ar')->nullable();
            $table->string('location')->nullable();
            $table->string('location_ar')->nullable();
            $table->string('rent')->nullable();
            $table->string('rent_ar')->nullable();
            $table->string('property_type')->nullable();
            $table->string('property_type_ar')->nullable();
            $table->string('beds')->nullable();
            $table->string('beds_ar')->nullable();
            $table->string('baths')->nullable();
            $table->string('baths_ar')->nullable();
            $table->string('price')->nullable();
            $table->string('price_ar')->nullable();
            $table->string('more_filters')->nullable();
            $table->string('more_filters_ar')->nullable();
            $table->string('find')->nullable();
            $table->string('find_ar')->nullable();
            $table->string('featured_properties')->nullable();
            $table->string('featured_properties_ar')->nullable();
            $table->string('title_five')->nullable();
            $table->string('title_five_ar')->nullable();
            $table->string('contact')->nullable();
            $table->string('contact_ar')->nullable();
            $table->string('btn_th_d_view')->nullable();
            $table->string('btn_th_d_view_ar')->nullable();
            $table->string('see_more')->nullable();
            $table->string('see_more_ar')->nullable();
            $table->string('why_choose')->nullable();
            $table->string('why_choose_ar')->nullable();
            $table->string('title_six')->nullable();
            $table->string('title_six_ar')->nullable();
            $table->string('sub_title_seven')->nullable();
            $table->string('sub_title_seven_ar')->nullable();
            $table->string('title_seven')->nullable();
            $table->string('title_seven_ar')->nullable();
            $table->string('paragraph_three')->nullable();
            $table->string('paragraph_three_ar')->nullable();
            $table->string('title_eight')->nullable();
            $table->string('title_eight_ar')->nullable();
            $table->string('paragraph_four')->nullable();
            $table->string('paragraph_four_ar')->nullable();
            $table->string('paragraph_five')->nullable();
            $table->string('paragraph_five_ar')->nullable();
            $table->string('title_nine')->nullable();
            $table->string('title_nine_ar')->nullable();
            $table->string('paragraph_six')->nullable();
            $table->string('paragraph_six_ar')->nullable();
            $table->string('title_ten')->nullable();
            $table->string('title_ten_ar')->nullable();
            $table->string('paragraph_seven')->nullable();
            $table->string('paragraph_seven_ar')->nullable();
            $table->string('title_eleven')->nullable();
            $table->string('title_eleven_ar')->nullable();
            $table->string('paragraph_eight')->nullable();
            $table->string('paragraph_eight_ar')->nullable();
            $table->string('about_us_txt')->nullable();
            $table->string('about_us_txt_ar')->nullable();
            $table->string('sub_title_seven')->nullable();
            $table->string('sub_title_seven_ar')->nullable();
            $table->string('paragraph_nine')->nullable();
            $table->string('paragraph_nine_ar')->nullable();
            $table->string('paragraph_ten')->nullable();
            $table->string('paragraph_ten_ar')->nullable();
            $table->string('services_title')->nullable();
            $table->string('services_title_ar')->nullable();
            $table->string('title_tweleve')->nullable();
            $table->string('title_tweleve_ar')->nullable();
            $table->string('title_thirteen')->nullable();
            $table->string('title_thirteen_ar')->nullable();
            $table->string('paragraph_eleven')->nullable();
            $table->string('paragraph_eleven_ar')->nullable();
            $table->string('title_fourteen')->nullable();
            $table->string('title_fourteen_ar')->nullable();
            $table->string('paragraph_tweleve')->nullable();
            $table->string('paragraph_tweleve_ar')->nullable();
            $table->string('title_fifteen')->nullable();
            $table->string('title_fifteen_ar')->nullable();
            $table->string('paragraph_thirteen')->nullable();
            $table->string('paragraph_thirteen_ar')->nullable();
            $table->string('title_sixteen')->nullable();
            $table->string('title_sixteen_ar')->nullable();
            $table->string('paragraph_fourteen')->nullable();
            $table->string('paragraph_fourteen_ar')->nullable();
            $table->string('title_seventeen')->nullable();
            $table->string('title_seventeen_ar')->nullable();
            $table->string('paragraph_fifteen')->nullable();
            $table->string('paragraph_fifteen_ar')->nullable();
            $table->string('title_eighteen')->nullable();
            $table->string('title_eighteen_ar')->nullable();
            $table->string('paragraph_sixteen')->nullable();
            $table->string('paragraph_sixteen_ar')->nullable();
            $table->string('sqm_u')->nullable();
            $table->string('sqm_u_ar')->nullable();
            $table->string('title_nineteen')->nullable();
            $table->string('title_nineteen_ar')->nullable();
            $table->string('value_one')->nullable();
            $table->string('title_twenty')->nullable();
            $table->string('title_twenty_ar')->nullable();
            $table->string('value_two')->nullable();
            $table->string('title_twenty_one')->nullable();
            $table->string('title_twenty_one_ar')->nullable();
            $table->string('value_three')->nullable();
            $table->string('title_twenty_two')->nullable();
            $table->string('title_twenty_two_ar')->nullable();
            $table->string('value_four')->nullable();
            $table->string('title_twenty_three')->nullable();
            $table->string('title_twenty_three_ar')->nullable();
            $table->string('title_twenty_four')->nullable();
            $table->string('title_twenty_four_ar')->nullable();
            $table->string('image_one')->nullable();
            $table->string('image_two')->nullable();
            $table->string('image_three')->nullable();
            $table->string('image_four')->nullable();
            $table->string('image_one_title')->nullable();
            $table->string('image_one_title_ar')->nullable();
            $table->string('image_one_sub_title')->nullable();
            $table->string('image_one_sub_title_ar')->nullable();
            $table->string('image_two_title')->nullable();
            $table->string('image_two_title_ar')->nullable();
            $table->string('image_two_sub_title')->nullable();
            $table->string('image_two_sub_title_ar')->nullable();
            $table->string('image_three_title')->nullable();
            $table->string('image_three_title_ar')->nullable();
            $table->string('image_three_sub_title')->nullable();
            $table->string('image_three_sub_title_ar')->nullable();
            $table->string('image_four_title')->nullable();
            $table->string('image_four_title_ar')->nullable();
            $table->string('image_four_sub_title')->nullable();
            $table->string('image_four_sub_title_ar')->nullable();
            $table->string('title_twenty_five')->nullable();
            $table->string('title_twenty_five_ar')->nullable();
            $table->string('btn_explore_txt')->nullable();
            $table->string('btn_explore_txt_ar')->nullable();
            $table->string('title_twenty_six')->nullable();
            $table->string('title_twenty_six_ar')->nullable(); 
            $table->string('btn_see_all')->nullable();
            $table->string('btn_see_all_ar')->nullable();
            $table->timestamps(); 
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('home_settings');
    }
};
